/// https://discord.com/developers/docs/reference#locales
@UnstableEnum<String>
public enum DiscordLocale: Sendable, Codable {
    case danish // "da"
    case german // "de"
    case englishUK // "en-GB"
    case englishUS // "en-US"
    case spanish // "es-ES"
    case french // "fr"
    case croatian // "hr"
    case italian // "it"
    case lithuanian // "lt"
    case hungarian // "hu"
    case dutch // "nl"
    case norwegian // "no"
    case polish // "pl"
    case portuguese // "pt-BR"
    case romanian // "ro"
    case finnish // "fi"
    case swedish // "sv-SE"
    case vietnamese // "vi"
    case turkish // "tr"
    case czech // "cs"
    case greek // "el"
    case bulgarian // "bg"
    case russian // "ru"
    case ukrainian // "uk"
    case hindi // "hi"
    case thai // "th"
    case chineseChina // "zh-CN"
    case japanese // "ja"
    case chineseTaiwan // "zh-TW"
    case korean // "ko"
}
